### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by nachogon1** [data-dot-all/dataall#1167]
### Describe the bug

Error while running cdk synth

Traceback (most recent call last):
  File "./deploy/app.py", line 15, in <module>
    from stacks.pipeline import PipelineStack
  File "/Users/xxxxxx/Projects/dataall/deploy/stacks/pipeline.py", line 16, in <module>
    from .backend_stage import BackendStage
  File "/Users/xxxxxx/Projects/dataall/deploy/stacks/backend_stage.py", line 4, in <module>
    from .backend_stack import BackendStack
  File "/Users/xxxxxx/Projects/dataall/deploy/stacks/backend_stack.py", line 25, in <module>
    from .trigger_function_stack import TriggerFunctionStack
  File "/Users/xxxxxxx/Projects/dataall/deploy/stacks/trigger_function_stack.py", line 14, in <module>
    class TriggerFunctionStack(pyNestedClass):
  File "/Users/xxxxxx/Projects/dataall/deploy/stacks/trigger_function_stack.py", line 26, in TriggerFunctionStack
    connectables: list[ec2.IConnectable] = [],
TypeError: 'type' object is not subscriptable

https://github.com/data-dot-all/dataall/blob/main/deploy/stacks/trigger_function_stack.py#L26 and
https://github.com/data-dot-all/dataall/blob/main/deploy/stacks/trigger_function_stack.py#L78

### How to Reproduce

Fresh deploy (I did not bootrstrapped accounts), installed requirements

`cdk synth`

### OS

Mac

### Python version

3.8.18

### AWS data.all version

2.3.0

### Additional context

I believe it should be a typed hint, `List` from `from typing import List` must be used instead in lines above.

**Comment by petrkalos** [comment]
A few references to Python 3.9 led me to believe that we support 3.9+ as such I used hinting as per [PEP585](https://peps.python.org/pep-0585/). Since this is not a good reason to require Python 3.9 I will submit a PR that will move to the old style of type hinting soon.

**Comment by noah-paige** [comment]
Hi @nachogon1 - #1170 should resolve the above TypeError you are facing, thanks for opening up this issue!
