### ISSUE TITLE
Docker-compose-ARG CONTAINER_UID - issue

### ISSUE THREAD

**Issue by sushant010** [data-dot-all/dataall#1651]
### Describe the bug

ARG CONTAINER_UID is not getting set after using the command **export UID && docker-compose up** 

### How to Reproduce

RUN
```
export UID && docker-compose up
```

### Expected behavior

Docker-compose should get successfully setting up with ARG CONTAINER_UID.

### Screenshots

Docker-image layers
![image](https://github.com/user-attachments/assets/ea7269bc-77ae-4a5b-bf05-879b3d8d9ab6)

Environment status in dataall console
![image](https://github.com/user-attachments/assets/c99a69a8-417e-4313-80e3-f15d65da01b0)

### OS

OS Name	Microsoft Windows 11 Enterprise, Version	10.0.22631 Build 22631

### Python version

3.9

### AWS data.all version

2.6.0

### Additional context

I was able to run this in 2.0.0 but recently after moving to 2.6.0 I'm facing this issue.
At the time of creation of environment the below error is occurring.

2024-10-18 16:54:36 [11:24:36] outdir: cdk.out
2024-10-18 16:54:36 [11:24:36] Reading cached notices from /home/cuser/.cdk/cache/notices.json
2024-10-18 16:54:36 EACCES: permission denied, open 'cdk.out/synth.lock.235_1'
2024-10-18 16:54:36 [11:24:36] Error: EACCES: permission denied, open 'cdk.out/synth.lock.235_1'
2024-10-18 16:54:36 Failed to deploy stack 65quv3au due to None
2024-10-18 16:54:36 Failed to deploy stack 65quv3au due to 'NoneType' object has no attribute 'split'
2024-10-18 16:54:36 ERROR:    Exception in ASGI application
2024-10-18 16:54:36 Traceback (most recent call last):
2024-10-18 16:54:36   File "/./dataall/base/cdkproxy/cdk_cli_wrapper.py", line 193, in deploy_cdk_stack
2024-10-18 16:54:36     AlarmService().trigger_stack_deployment_failure_alarm(stack=stack)
2024-10-18 16:54:36   File "/./dataall/base/utils/alarm_service.py", line 30, in trigger_stack_deployment_failure_alarm
2024-10-18 16:54:36     https://{self.region}.console.aws.amazon.com/cloudwatch/deeplink.js?region=eu-west-1#logsV2:log-groups/log-group/$252Fdataall$252F{self.envname}$252Fecs$252Fcdkproxy/log-events/task$252Fcontainer$252F{stack.EcsTaskArn.split('/')[-1]}
2024-10-18 16:54:36 AttributeError: 'NoneType' object has no attribute 'split'
2024-10-18 16:54:36 
2024-10-18 16:54:36 During handling of the above exception, another exception occurred:
2024-10-18 16:54:36 
2024-10-18 16:54:36 Traceback (most recent call last):
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
2024-10-18 16:54:36     result = await app(self.scope, self.receive, self.send)
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
2024-10-18 16:54:36     return await self.app(scope, receive, send)
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
2024-10-18 16:54:36     await super().__call__(scope, receive, send)
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
2024-10-18 16:54:36     await self.middleware_stack(scope, receive, send)
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-10-18 16:54:36     raise exc
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-10-18 16:54:36     await self.app(scope, receive, _send)
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-10-18 16:54:36     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-10-18 16:54:36     raise exc
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-10-18 16:54:36     await app(scope, receive, sender)
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 758, in __call__
2024-10-18 16:54:36     await self.middleware_stack(scope, receive, send)
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 778, in app
2024-10-18 16:54:36     await route.handle(scope, receive, send)
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 299, in handle
2024-10-18 16:54:36     await self.app(scope, receive, send)
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 79, in app
2024-10-18 16:54:36     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-10-18 16:54:36     raise exc
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-10-18 16:54:36     await app(scope, receive, sender)
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
2024-10-18 16:54:36     await response(scope, receive, send)
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 161, in __call__
2024-10-18 16:54:36     await self.background()
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/starlette/background.py", line 45, in __call__
2024-10-18 16:54:36     await task()
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/starlette/background.py", line 30, in __call__
2024-10-18 16:54:36     await run_in_threadpool(self.func, *self.args, **self.kwargs)
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
2024-10-18 16:54:36     return await anyio.to_thread.run_sync(func, *args)
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-10-18 16:54:36     return await get_async_backend().run_sync_in_worker_thread(
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
2024-10-18 16:54:36     return await future
2024-10-18 16:54:36   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 943, in run
2024-10-18 16:54:36     result = context.run(func, *args)
2024-10-18 16:54:36   File "/./dataall/base/cdkproxy/cdk_cli_wrapper.py", line 197, in deploy_cdk_stack
2024-10-18 16:54:36     AlarmService().trigger_stack_deployment_failure_alarm(stack=stack)
2024-10-18 16:54:36   File "/./dataall/base/utils/alarm_service.py", line 30, in trigger_stack_deployment_failure_alarm
2024-10-18 16:54:36     https://{self.region}.console.aws.amazon.com/cloudwatch/deeplink.js?region=eu-west-1#logsV2:log-groups/log-group/$252Fdataall$252F{self.envname}$252Fecs$252Fcdkproxy/log-events/task$252Fcontainer$252F{stack.EcsTaskArn.split('/')[-1]}
2024-10-18 16:54:36 AttributeError: 'NoneType' object has no attribute 'split'

**Comment by noah-paige** [comment]
Hi @sushant010 - I just tried to replicate this error and am not running into the same issues as above. Since v2.0 we drilled down permissioning of the local container images to no longer run as root. Can you ensure the following:

- Env Variable of UID is properly set before starting docker container (for windows I believe it will be `set UID=VALUE` instead of `export` 
- Re build the container by running `docker compose up --build` to ensure all latest changes reflected

**Comment by sushant010** [comment]
Hi @noah-paige,
Can you please let us know what's the value of **VALUE**?

**Comment by sushant010** [comment]
Hi @noah-paige,
The UID value is properly set but after rebuilding the container the above mentioned error persists,  at the time of creation of environment, stack deployment is failing.

Error -- (Same can be found in additional context)

2024-10-18 16:54:36 [11:24:36] outdir: cdk.out
2024-10-18 16:54:36 [11:24:36] Reading cached notices from /home/cuser/.cdk/cache/notices.json
2024-10-18 16:54:36 EACCES: permission denied, open 'cdk.out/synth.lock.235_1'
2024-10-18 16:54:36 [11:24:36] Error: EACCES: permission denied, open 'cdk.out/synth.lock.235_1'
2024-10-18 16:54:36 Failed to deploy stack 65quv3au due to None
2024-10-18 16:54:36 Failed to deploy stack 65quv3au due to 'NoneType' object has no attribute 'split'

**Comment by noah-paige** [comment]
@sushant010 - do you have exists `cdk.out` directory at `dataall/backend/dataall/base/cdkproxy/cdk.out` - if so could you remove and try again looks like permissions to open that directory are not there may have been created before use of docker user

**Comment by sushant010** [comment]
It worked @noah-paige.
Thanks a lot!!

**Comment by noah-paige** [comment]
no problem @sushant010 - closing this issue as resolved!
